version: '3'
services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
 
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /:/srv
      - filebrowser_data:/srv/data  # 新增挂载卷用于持久化数据
    restart: unless-stopped
    ports:
      - 8081:80
      
volumes:
  portainer_data:
  filebrowser_data:  # 新增持久化数据卷
