version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:    
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 8080:80
    volumes:
      - /:/srv
      - /path/filebrowser.db:/database.db
      - /path/.filebrowser.json:/.filebrowser.json
