version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
  warp-proxy:
    image: yarmak/warp-proxy
    ports:
      - 40000:40000
    restart: always
    mem_limit: 100M
    environment:
      - "TZ=Asia/Shanghai"
  x-ui:
    image: enwaiax/x-ui
    restart: unless-stopped
    network_mode: host
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
   

