version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
  warp-proxy:
    image: yarmak/warp-proxy
    ports:
      - 40000:40000
    restart: always
    mem_limit: 100M
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: zoeyvid/nginx-proxy-manager
    restart: always
    network_mode: host
    volumes:
      - "/opt/npm:/data"
      - "/var/www:/var/www"
    environment:
      - "TZ=Asia/Shanghai"
