version: "3"
services:
  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /etc/alist:/opt/alist/data
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
  x-ui:
    image: enwaiax/x-ui
    restart: unless-stopped
    network_mode: host
  nginx:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt
