version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
  warp-proxy:
    image: yarmak/warp-proxy
    ports:
      - 40000:40000
    restart: always
    mem_limit: 100M
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - 5700:5700
    volumes:
      - /root/ql/data:/ql/data
  zerotier-one:
    image: henrist/zerotier-one
    container_name: zerotier-one
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    mem_limit: 100m
  x-ui:
    image: enwaiax/x-ui:latest
    restart: unless-stopped
    networks:
      - host
    volumes:
      - ./db:/etc/x-ui/
      - ./cert:/root/cert/
version: "3.8"

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: zoeyvid/nginx-proxy-manager
    restart: always
    network_mode: host
    volumes:
      - "/opt/npm:/data"
      # - "/var/www:/var/www" # 可选项，如果您想将其用作HTML/PHP的Web服务器
      # - "/opt/npm-letsencrypt:/etc/letsencrypt" # 仅在第一次从原始nginx-proxy-manager迁移到此分支时需要
    environment:
      - "TZ=Asia/Shanghai" # 设置时区为中国上海
