version: "3"
services:
  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /etc/alist:/opt/alist/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  x-ui:
    image: enwaiax/x-ui
    restart: unless-stopped
    network_mode: host

  nginx:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt

  warp-proxy:
    image: yarmak/warp-proxy
    ports:
      - 40000:40000
    restart: always

  chatgpt-web:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      - OPENAI_API_KEY=xxxxxx
      - OPENAI_ACCESS_TOKEN=xxxxxx
      - OPENAI_API_BASE_URL=xxxx
      - OPENAI_API_MODEL=xxxx
      - API_REVERSE_PROXY=xxx
      - AUTH_SECRET_KEY=xxx
      - MAX_REQUEST_PER_HOUR=0
      - TIMEOUT_MS=60000
      - SOCKS_PROXY_HOST=xxxx
      - SOCKS_PROXY_PORT=xxxx

  qinglong:
    image: whyour/qinglong
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - 5700:5700
    volumes:
      - /root/ql/data:/ql/data
