version: "3"
services:

  # Alist Service
  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /etc/alist:/opt/alist/data
 
  # Watchtower Service
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  # X-UI Service
  x-ui:
    image: enwaiax/x-ui
    restart: unless-stopped
    network_mode: host

  # Nginx Service
  nginx:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt

  # Warp Proxy Service
  warp-proxy:
    image: yarmak/warp-proxy
    ports:
      - 40000:40000
    restart: always
